hasCuisine(maroush, lebanese).
hasCuisine(maroush, middleeastern).
priceRange(maroush, low).
mealTypes(maroush, lunch).
mealTypes(maroush, dinner).
distance(maroush, 9).
isVegetarian(maroush, y).
glutenFree(maroush, unknown).
hasLanguage(maroush, german).
hasLanguage(maroush, english).
hasLanguage(maroush, arabic).
transportation(maroush, walk).
hasCuisine(burgermeisterkottbussertor, american).
priceRange(burgermeisterkottbussertor, low).
mealTypes(burgermeisterkottbussertor, lunch).
mealTypes(burgermeisterkottbussertor, dinner).
distance(burgermeisterkottbussertor, 12).
isVegetarian(burgermeisterkottbussertor, y).
glutenFree(burgermeisterkottbussertor, unknown).
hasLanguage(burgermeisterkottbussertor, german).
hasLanguage(burgermeisterkottbussertor, english).
transportation(burgermeisterkottbussertor, walk).
hasCuisine(basmah, sudanese).
hasCuisine(basmah, mediterranean).
priceRange(basmah, low).
mealTypes(basmah, lunch).
mealTypes(basmah, dinner).
distance(basmah, 15).
isVegetarian(basmah, y).
glutenFree(basmah, unknown).
hasLanguage(basmah, german).
hasLanguage(basmah, english).
hasLanguage(basmah, arabic).
transportation(basmah, walk).
transportation(basmah, bus).
hasCuisine(mundvoll, international).
priceRange(mundvoll, medium).
mealTypes(mundvoll, breakfast).
mealTypes(mundvoll, brunch).
mealTypes(mundvoll, lunch).
mealTypes(mundvoll, dinner).
distance(mundvoll, 6).
isVegetarian(mundvoll, y).
glutenFree(mundvoll, y).
hasLanguage(mundvoll, german).
hasLanguage(mundvoll, english).
transportation(mundvoll, walk).
hasCuisine(paglia, italian).
hasCuisine(paglia, mediterranean).
priceRange(paglia, medium).
mealTypes(paglia, brunch).
mealTypes(paglia, lunch).
mealTypes(paglia, dinner).
distance(paglia, 9).
isVegetarian(paglia, y).
glutenFree(paglia, unknown).
hasLanguage(paglia, german).
hasLanguage(paglia, english).
transportation(paglia, walk).
hasCuisine(milchzucker, international).
priceRange(milchzucker, medium).
mealTypes(milchzucker, breakfast).
mealTypes(milchzucker, brunch).
mealTypes(milchzucker, lunch).
mealTypes(milchzucker, dinner).
distance(milchzucker, 12).
isVegetarian(milchzucker, y).
glutenFree(milchzucker, y).
hasLanguage(milchzucker, german).
hasLanguage(milchzucker, english).
transportation(milchzucker, walk).
hasCuisine(yafo, israeli).
priceRange(yafo, medium).
mealTypes(yafo, lunch).
mealTypes(yafo, dinner).
distance(yafo, 20).
isVegetarian(yafo, y).
glutenFree(yafo, n).
hasLanguage(yafo, german).
hasLanguage(yafo, english).
transportation(yafo, bus).
transportation(yafo, taxi).
hasCuisine(jambo, african).
priceRange(jambo, medium).
mealTypes(jambo, lunch).
mealTypes(jambo, dinner).
distance(jambo, 25).
isVegetarian(jambo, y).
glutenFree(jambo, n).
hasLanguage(jambo, german).
hasLanguage(jambo, english).
transportation(jambo, bus).
transportation(jambo, taxi).
hasCuisine(westberlin, european).
priceRange(westberlin, medium).
mealTypes(westberlin, breakfast).
mealTypes(westberlin, brunch).
mealTypes(westberlin, lunch).
distance(westberlin, 35).
isVegetarian(westberlin, y).
glutenFree(westberlin, y).
hasLanguage(westberlin, german).
hasLanguage(westberlin, english).
transportation(westberlin, metro).
transportation(westberlin, bus).
transportation(westberlin, taxi).
hasCuisine(amrit, indian).
priceRange(amrit, medium).
mealTypes(amrit, lunch).
mealTypes(amrit, dinner).
distance(amrit, 25).
isVegetarian(amrit, y).
glutenFree(amrit, n).
hasLanguage(amrit, german).
hasLanguage(amrit, english).
hasLanguage(amrit, hindi).
transportation(amrit, metro).
transportation(amrit, taxi).
hasCuisine(quepasamexicana, mexican).
priceRange(quepasamexicana, low).
mealTypes(quepasamexicana, breakfast).
mealTypes(quepasamexicana, brunch).
mealTypes(quepasamexicana, lunch).
distance(quepasamexicana, 10).
isVegetarian(quepasamexicana, y).
glutenFree(quepasamexicana, n).
hasLanguage(quepasamexicana, german).
hasLanguage(quepasamexicana, spanish).
transportation(quepasamexicana, walk).
transportation(quepasamexicana, bus).
hasCuisine(hasirburger, turkish).
priceRange(hasirburger, medium).
mealTypes(hasirburger, lunch).
mealTypes(hasirburger, dinner).
distance(hasirburger, 10).
isVegetarian(hasirburger, n).
glutenFree(hasirburger, n).
hasLanguage(hasirburger, german).
hasLanguage(hasirburger, turkish).
transportation(hasirburger, walk).
transportation(hasirburger, bus).
hasCuisine(kreuzbergerweltlaterne, greek).
priceRange(kreuzbergerweltlaterne, medium).
mealTypes(kreuzbergerweltlaterne, breakfast).
mealTypes(kreuzbergerweltlaterne, brunch).
mealTypes(kreuzbergerweltlaterne, lunch).
distance(kreuzbergerweltlaterne, 15).
isVegetarian(kreuzbergerweltlaterne, y).
glutenFree(kreuzbergerweltlaterne, n).
hasLanguage(kreuzbergerweltlaterne, german).
hasLanguage(kreuzbergerweltlaterne, greek).
hasLanguage(kreuzbergerweltlaterne, english).
transportation(kreuzbergerweltlaterne, bus).
transportation(kreuzbergerweltlaterne, taxi).
hasCuisine(wonderwaffel, international).
priceRange(wonderwaffel, medium).
mealTypes(wonderwaffel, breakfast).
mealTypes(wonderwaffel, brunch).
distance(wonderwaffel, 18).
isVegetarian(wonderwaffel, y).
glutenFree(wonderwaffel, y).
hasLanguage(wonderwaffel, german).
hasLanguage(wonderwaffel, english).
transportation(wonderwaffel, metro).
transportation(wonderwaffel, bus).
transportation(wonderwaffel, taxi).
hasCuisine(eden, vietnamese).
priceRange(eden, medium).
mealTypes(eden, lunch).
mealTypes(eden, dinner).
distance(eden, 35).
isVegetarian(eden, y).
glutenFree(eden, n).
hasLanguage(eden, german).
hasLanguage(eden, vietnamese).
transportation(eden, metro).
transportation(eden, bus).
transportation(eden, taxi).
hasCuisine(nanoosh, mediterranean).
priceRange(nanoosh, medium).
mealTypes(nanoosh, breakfast).
mealTypes(nanoosh, brunch).
mealTypes(nanoosh, lunch).
distance(nanoosh, 35).
isVegetarian(nanoosh, y).
glutenFree(nanoosh, n).
hasLanguage(nanoosh, german).
hasLanguage(nanoosh, english).
transportation(nanoosh, bus).
transportation(nanoosh, taxi).
hasCuisine(lapiadina, italian).
priceRange(lapiadina, low).
mealTypes(lapiadina, brunch).
mealTypes(lapiadina, lunch).
mealTypes(lapiadina, dinner).
distance(lapiadina, 7).
isVegetarian(lapiadina, y).
glutenFree(lapiadina, y).
hasLanguage(lapiadina, german).
hasLanguage(lapiadina, italian).
hasLanguage(lapiadina, english).
transportation(lapiadina, walk).
hasCuisine(santamaria, mexican).
priceRange(santamaria, low).
mealTypes(santamaria, lunch).
mealTypes(santamaria, dinner).
distance(santamaria, 9).
isVegetarian(santamaria, y).
glutenFree(santamaria, n).
hasLanguage(santamaria, german).
hasLanguage(santamaria, spanish).
transportation(santamaria, walk).
hasCuisine(sushiforyou, japanese).
priceRange(sushiforyou, medium).
mealTypes(sushiforyou, lunch).
mealTypes(sushiforyou, dinner).
distance(sushiforyou, 11).
isVegetarian(sushiforyou, y).
glutenFree(sushiforyou, y).
hasLanguage(sushiforyou, german).
hasLanguage(sushiforyou, english).
hasLanguage(sushiforyou, japanese).
transportation(sushiforyou, walk).
transportation(sushiforyou, bus).
hasCuisine(hofbraeuwirtshaus, german).
priceRange(hofbraeuwirtshaus, medium).
mealTypes(hofbraeuwirtshaus, lunch).
mealTypes(hofbraeuwirtshaus, brunch).
mealTypes(hofbraeuwirtshaus, dinner).
distance(hofbraeuwirtshaus, 40).
isVegetarian(hofbraeuwirtshaus, y).
glutenFree(hofbraeuwirtshaus, n).
hasLanguage(hofbraeuwirtshaus, german).
hasLanguage(hofbraeuwirtshaus, english).
transportation(hofbraeuwirtshaus, metro).
transportation(hofbraeuwirtshaus, bus).
transportation(hofbraeuwirtshaus, taxi).
hasCuisine(pila, german).
priceRange(pila, low).
mealTypes(pila, breakfast).
mealTypes(pila, brunch).
distance(pila, 50).
isVegetarian(pila, y).
glutenFree(pila, y).
hasLanguage(pila, german).
transportation(pila, metro).
transportation(pila, bus).
transportation(pila, taxi).
hasCuisine(huating, chinese).
priceRange(huating, medium).
mealTypes(huating, lunch).
mealTypes(huating, brunch).
mealTypes(huating, dinner).
distance(huating, 20).
isVegetarian(huating, y).
glutenFree(huating, n).
hasLanguage(huating, german).
hasLanguage(huating, english).
transportation(huating, taxi).
hasCuisine(longmarchcanteen, chinese).
priceRange(longmarchcanteen, high).
mealTypes(longmarchcanteen, lunch).
mealTypes(longmarchcanteen, dinner).
distance(longmarchcanteen, 10).
isVegetarian(longmarchcanteen, y).
glutenFree(longmarchcanteen, y).
hasLanguage(longmarchcanteen, german).
hasLanguage(longmarchcanteen, english).
hasLanguage(longmarchcanteen, chinese).
transportation(longmarchcanteen, walk).
transportation(longmarchcanteen, taxi).
hasCuisine(shezan, indian).
priceRange(shezan, medium).
mealTypes(shezan, lunch).
mealTypes(shezan, brunch).
mealTypes(shezan, dinner).
distance(shezan, 18).
isVegetarian(shezan, y).
glutenFree(shezan, n).
hasLanguage(shezan, german).
hasLanguage(shezan, english).
hasLanguage(shezan, hindi).
transportation(shezan, walk).
transportation(shezan, bus).
hasCuisine(lemongrass, thai).
priceRange(lemongrass, medium).
mealTypes(lemongrass, breakfast).
mealTypes(lemongrass, brunch).
distance(lemongrass, 40).
isVegetarian(lemongrass, y).
glutenFree(lemongrass, n).
hasLanguage(lemongrass, german).
hasLanguage(lemongrass, english).
hasLanguage(lemongrass, thai).
transportation(lemongrass, metro).
transportation(lemongrass, bus).
transportation(lemongrass, taxi).
hasCuisine(rissani, morrocan).
priceRange(rissani, low).
mealTypes(rissani, lunch).
mealTypes(rissani, brunch).
mealTypes(rissani, dinner).
distance(rissani, 15).
isVegetarian(rissani, y).
glutenFree(rissani, n).
hasLanguage(rissani, german).
hasLanguage(rissani, arabic).
transportation(rissani, walk).
transportation(rissani, bus).
hasCuisine(richard, french).
priceRange(richard, high).
mealTypes(richard, lunch).
mealTypes(richard, dinner).
distance(richard, 15).
isVegetarian(richard, y).
glutenFree(richard, y).
hasLanguage(richard, german).
hasLanguage(richard, french).
transportation(richard, walk).
transportation(richard, bus).
hasCuisine(spindler, european).
priceRange(spindler, medium).
mealTypes(spindler, lunch).
mealTypes(spindler, brunch).
mealTypes(spindler, dinner).
distance(spindler, 18).
isVegetarian(spindler, y).
glutenFree(spindler, y).
hasLanguage(spindler, german).
hasLanguage(spindler, french).
transportation(spindler, walk).
transportation(spindler, bus).
hasCuisine(knofifeinkost, turkish).
priceRange(knofifeinkost, medium).
mealTypes(knofifeinkost, lunch).
mealTypes(knofifeinkost, brunch).
mealTypes(knofifeinkost, dinner).
distance(knofifeinkost, 45).
isVegetarian(knofifeinkost, y).
glutenFree(knofifeinkost, n).
hasLanguage(knofifeinkost, german).
hasLanguage(knofifeinkost, turkish).
transportation(knofifeinkost, metro).
transportation(knofifeinkost, bus).
transportation(knofifeinkost, taxi).
hasCuisine(mabuhay, indonesian).
priceRange(mabuhay, low).
mealTypes(mabuhay, lunch).
mealTypes(mabuhay, dinner).
distance(mabuhay, 50).
isVegetarian(mabuhay, y).
glutenFree(mabuhay, y).
hasLanguage(mabuhay, german).
hasLanguage(mabuhay, english).
transportation(mabuhay, bus).
transportation(mabuhay, taxi).
